defaults:
  - hydra: hydra_simple
  - _self_


name: 3DCorridorAdHoc

logger:
  load_dir: ${name}
  log_grad: false
  project: diversity-gen
  entity: uoe-agents-div-team
  logger_period: 0.0025
  save_model: true

# # Data collection-related parameters
env:
  name: cookingZooEnv-tiny-250-v0
  parallel:
    adhoc_collection: 160
    eval_collection: 16
  model_id: 100
  model_load_dir: /Volumes/home/consolidated_aht_params/Overcooked/TrajeDi1/1/models

env_eval:
  name: cookingZooEnv-tiny-250-adhoc-v0

eval_params:
  eval_mode: alg_xp
  num_eval_heuristics: 9
  num_seeds: 5
  per_seed_eval_eps: 48
  all_params_dir: /Volumes/consolidated_aht_params/Overcooked

train:
  timesteps_per_update: 8
  gamma: 0.99
  gamma_act_jsd: 0.1
  target_update_rate: 1e-3
  lr: 1e-4
  max_grad_norm: 10.0

run:
  use_cuda: true
  num_eval_episodes: 64
  seed: 0
  eval_seed: 500
  total_checkpoints: 40
  load_from_checkpoint: -1
  load_dir: /home/MAACBasedOptim/outputs/3DCorridorAdHoc/2022-12-15/18-58-49

# # Training details
# separate_controllers: false

populations:
  num_populations: 4
  # separate_controllers: false

model:
  with_gnn_controllers: false
  parameter_sharing: false
  separate_model_in_populations: true
  enc_mid_dim1: 100
  enc_mid_dim2: 100
  gnn_h_dim1: 200
  gnn_h_dim2: 200
  gnn_out_dim: 100
  agent_rep_size: 128
  actor_dims:
    - 256
    - 256
    - 128
  critic_dims:
    - 256
    - 256
    - 128

plastic:
  eta: 1.0

loss_weights:
  diversity_loss: values
  obs_decoding_loss: 0.5
  acts_decoding_loss: 5.0
  critic_loss: 5.0
  actor_loss: 25.0
  entropy_regularizer_loss: 0.001

any_play:
  with_any_play: false
